### PR TITLE
[WIP] Adding Carthage support

### PR DESCRIPTION
**Pull request by dodikk**
* Added xcodeproj
* Added workspace and shared target
* Added umbrella header
* Added search path and files to the project according to the podspec

# !!! Warning

Did not figure yet how to compile due to issues with `bindtextdomain (PACKAGE, LOCALEDIR);` macro
screen shot 2017-02-16 at 10 44 00 am

### CODE REVIEW

**Comment by chrisballinger** [comment]
I'm guessing there are some pre-processor definitions that need to be passed during compilation. Check here from the podspec:

https://github.com/chrisballinger/libidn-podspec/blob/master/libidn.podspec#L34

```ruby
  s.compiler_flags = '-DHAVE_CONFIG_H', '-DLIBIDN_BUILDING', '-DLOCALEDIR=\"/usr/share/locale\"'
```

**Comment by dodikk** [comment]
>> I'm guessing there are some pre-processor definitions that need to be passed during compilation. Check here from the podspec:

I have applied those already
https://github.com/chrisballinger/libidn-podspec/pull/3/files#diff-429eab7a0871a898c5759c922ad8cf24R607

**Comment by chrisballinger** [comment]
I think I got everything all figured out. Only wasted a day and a half fighting against Xcode, CocoaPods, and libidn's ancient build system. https://github.com/chrisballinger/libidn-framework/tree/libidn-133-framework

Waiting for the Travis build to pass.

**Comment by dodikk** [comment]
Thank you so much. Not sure how long it would take me to do that...

**Comment by chrisballinger** [comment]
@dodikk It was a nightmare to be honest :)

**Pull request merged**
